"""initial_tables_and_seed

Revision ID: 26c131c1f8bc
Revises: 
Create Date: 2025-11-29 14:38:09.213777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c131c1f8bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_index(op.f('ix_monthly_schedules_id'), 'monthly_schedules', ['id'], unique=False)
    op.create_table('shift_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simbolo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('inicio', sa.String(length=10), nullable=False),
    sa.Column('fim', sa.String(length=10), nullable=False),
    sa.Column('etapa', sa.Integer(), nullable=True),
    sa.Column('complementar', sa.Integer(), nullable=True),
    sa.Column('turno_pricipal_id', sa.Integer(), nullable=True),
    sa.Column('turno_noturno', sa.Integer(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_definitions_id'), 'shift_definitions', ['id'], unique=False)
    op.create_table('instructor_capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_schedule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('manha', 'tarde', 'pernoite', name='shift'), nullable=False),
    sa.Column('total_instructors', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monthly_schedule_id'], ['monthly_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monthly_schedule_id', 'date', 'shift', name='uix_instructor_capacity_per_month')
    )
    op.create_index(op.f('ix_instructor_capacity_id'), 'instructor_capacity', ['id'], unique=False)
    op.create_table('trainees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_schedule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['monthly_schedule_id'], ['monthly_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monthly_schedule_id', 'name', name='uix_trainee_per_month')
    )
    op.create_index(op.f('ix_trainees_id'), 'trainees', ['id'], unique=False)
    op.create_table('trainee_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_schedule_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('manha', 'tarde', 'pernoite', name='shift'), nullable=False),
    sa.ForeignKeyConstraint(['monthly_schedule_id'], ['monthly_schedules.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainee_id', 'date', name='uix_trainee_assignment_day')
    )
    op.create_index(op.f('ix_trainee_assignments_id'), 'trainee_assignments', ['id'], unique=False)
    op.create_table('trainee_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_schedule_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('manha', 'tarde', 'pernoite', name='shift'), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['monthly_schedule_id'], ['monthly_schedules.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainee_id', 'date', 'shift', name='uix_trainee_availability')
    )
    op.create_index(op.f('ix_trainee_availability_id'), 'trainee_availability', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainee_availability_id'), table_name='trainee_availability')
    op.drop_table('trainee_availability')
    op.drop_index(op.f('ix_trainee_assignments_id'), table_name='trainee_assignments')
    op.drop_table('trainee_assignments')
    op.drop_index(op.f('ix_trainees_id'), table_name='trainees')
    op.drop_table('trainees')
    op.drop_index(op.f('ix_instructor_capacity_id'), table_name='instructor_capacity')
    op.drop_table('instructor_capacity')
    op.drop_index(op.f('ix_shift_definitions_id'), table_name='shift_definitions')
    op.drop_table('shift_definitions')
    op.drop_index(op.f('ix_monthly_schedules_id'), table_name='monthly_schedules')
    op.drop_table('monthly_schedules')
    # ### end Alembic commands ###
