"""add_reason_to_availability

Revision ID: b7576b9fcbf2
Revises: 26c131c1f8bc
Create Date: 2025-11-29 18:12:39.015658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7576b9fcbf2'
down_revision: Union[str, None] = '26c131c1f8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainee_availability', sa.Column('reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainee_availability', 'reason')
    # ### end Alembic commands ###
